export const portfolioTheme = {
  color: {
    canvas: 'var(--color-canvas)',
    surface: 'var(--color-surface)',
    ink: 'var(--color-ink)',
    inkSecondary: 'var(--color-ink-secondary)',
    muted: 'var(--color-muted)',
    accent: 'var(--color-accent)',
    accentSoft: 'var(--color-accent-soft)',
    focus: 'var(--color-focus)',
    tealDeep: 'var(--color-teal-deep)',
    teal: 'var(--color-teal)',
    border: 'var(--color-border)',
    warn: 'var(--color-warn)',
    success: 'var(--color-success)',
    interiorCanvas: 'var(--color-interior-canvas)',
    evidenceGroupSecondary: 'var(--color-evidence-group-secondary)',
  },
  space: {
    one: 'var(--space-1)',
    xs: 'var(--space-2)',
    sm: 'var(--space-3)',
    md: 'var(--space-4)',
    m: 'var(--space-5)',
    lg: 'var(--space-6)',
    l: 'var(--space-7)',
    xl: 'var(--space-8)',
    xxl: 'var(--space-12)',
    xxxl: 'var(--space-16)',
    xxxxl: 'var(--space-20)',
    section: 'var(--space-24)',
  },
  size: {
    siteHeader: 'var(--size-site-header)',
  },
  font: {
    display: 'var(--font-display)',
    body: 'var(--font-body)',
    code: 'var(--font-code)',
    siteSans: 'var(--font-site-sans)',
    articleSerif: 'var(--font-article-serif)',
    technical: 'var(--font-technical)',
  },
  type: {
    siteDisplaySize: 'var(--type-site-display-size)',
    siteDisplayLeading: 'var(--type-site-display-leading)',
    siteDisplayTracking: 'var(--type-site-display-tracking)',
    sectionSize: 'var(--type-section-size)',
    siteBodySize: 'var(--type-site-body-size)',
    siteBodyLeading: 'var(--type-site-body-leading)',
    articleBodySize: 'var(--type-article-body-size)',
    articleBodyLeading: 'var(--type-article-body-leading)',
    metadataSize: 'var(--type-metadata-size)',
    captionSize: 'var(--type-caption-size)',
    codeSize: 'var(--type-code-size)',
  },
  layout: {
    readableLine: 'var(--line-readable)',
    maxWidth: 'var(--layout-max-width)',
    readingMeasure: 'var(--measure-reading)',
  },
  motion: {
    fast: 'var(--duration-fast)',
    state: 'var(--duration-state)',
    easeOut: 'var(--ease-out)',
  },
} as const

export type PortfolioTheme = typeof portfolioTheme
