export { EditorialPullQuote } from './EditorialPullQuote'
export { EditorialAside } from './EditorialAside'
export type { EditorialAsideProps } from './EditorialAside'
export { EditorialFootnote } from './EditorialFootnote'
export type { EditorialFootnoteProps } from './EditorialFootnote'
export { EditorialHeading } from './EditorialHeading'
export type { EditorialHeadingWrap } from './EditorialHeading'
