export const SILK_COMMISSION_08_REVIEW_FRAME_WIDTH = 2142
export const SILK_COMMISSION_08_REVIEW_FRAME_HEIGHT = 734
export const SILK_COMMISSION_08_REVIEW_DERIVATIVE_WIDTH = 1750
export const SILK_COMMISSION_08_REVIEW_DERIVATIVE_HEIGHT = 600

export const SILK_COMMISSION_08_REVIEW_VIEWPORT = Object.freeze({
  left: 78,
  right: 1991,
  top: 256,
  bottom: 487,
})

export const SILK_COMMISSION_08_REVIEW_ALPHA_THRESHOLD = 240
export const SILK_COMMISSION_08_REVIEW_COVERAGE_BAND = 2

const viewportWidth = SILK_COMMISSION_08_REVIEW_VIEWPORT.right - SILK_COMMISSION_08_REVIEW_VIEWPORT.left + 1
const viewportHeight = SILK_COMMISSION_08_REVIEW_VIEWPORT.bottom - SILK_COMMISSION_08_REVIEW_VIEWPORT.top + 1

export const SILK_COMMISSION_08_REVIEW_VIEWPORT_INSETS = Object.freeze({
  left: `${(SILK_COMMISSION_08_REVIEW_VIEWPORT.left / SILK_COMMISSION_08_REVIEW_FRAME_WIDTH) * 100}%`,
  top: `${(SILK_COMMISSION_08_REVIEW_VIEWPORT.top / SILK_COMMISSION_08_REVIEW_FRAME_HEIGHT) * 100}%`,
  width: `${(viewportWidth / SILK_COMMISSION_08_REVIEW_FRAME_WIDTH) * 100}%`,
  height: `${(viewportHeight / SILK_COMMISSION_08_REVIEW_FRAME_HEIGHT) * 100}%`,
})
