export const SILK_COMMISSION_07_REVIEW_FRAME_WIDTH = 1671
export const SILK_COMMISSION_07_REVIEW_FRAME_HEIGHT = 941
export const SILK_COMMISSION_07_REVIEW_PORTRAIT_FRAME_WIDTH = 941
export const SILK_COMMISSION_07_REVIEW_PORTRAIT_FRAME_HEIGHT = 1671
export const SILK_COMMISSION_07_REVIEW_ALPHA_THRESHOLD = 240
export const SILK_COMMISSION_07_REVIEW_COVERAGE_BAND = 2

export const SILK_COMMISSION_07_REVIEW_VIEWPORT = {
  left: 112,
  right: 1522,
  top: 166,
  bottom: 812,
} as const

export const SILK_COMMISSION_07_REVIEW_VIEWPORT_INSETS = {
  top: `${(SILK_COMMISSION_07_REVIEW_VIEWPORT.top / SILK_COMMISSION_07_REVIEW_FRAME_HEIGHT) * 100}%`,
  right: `${((SILK_COMMISSION_07_REVIEW_FRAME_WIDTH - SILK_COMMISSION_07_REVIEW_VIEWPORT.right) / SILK_COMMISSION_07_REVIEW_FRAME_WIDTH) * 100}%`,
  bottom: `${((SILK_COMMISSION_07_REVIEW_FRAME_HEIGHT - SILK_COMMISSION_07_REVIEW_VIEWPORT.bottom) / SILK_COMMISSION_07_REVIEW_FRAME_HEIGHT) * 100}%`,
  left: `${(SILK_COMMISSION_07_REVIEW_VIEWPORT.left / SILK_COMMISSION_07_REVIEW_FRAME_WIDTH) * 100}%`,
} as const

export const SILK_COMMISSION_07_REVIEW_PORTRAIT_VIEWPORT = {
  left: 143,
  right: 837,
  top: 198,
  bottom: 1475,
} as const

export const SILK_COMMISSION_07_REVIEW_PORTRAIT_VIEWPORT_INSETS = {
  top: `${(SILK_COMMISSION_07_REVIEW_PORTRAIT_VIEWPORT.top / SILK_COMMISSION_07_REVIEW_PORTRAIT_FRAME_HEIGHT) * 100}%`,
  right: `${((SILK_COMMISSION_07_REVIEW_PORTRAIT_FRAME_WIDTH - SILK_COMMISSION_07_REVIEW_PORTRAIT_VIEWPORT.right) / SILK_COMMISSION_07_REVIEW_PORTRAIT_FRAME_WIDTH) * 100}%`,
  bottom: `${((SILK_COMMISSION_07_REVIEW_PORTRAIT_FRAME_HEIGHT - SILK_COMMISSION_07_REVIEW_PORTRAIT_VIEWPORT.bottom) / SILK_COMMISSION_07_REVIEW_PORTRAIT_FRAME_HEIGHT) * 100}%`,
  left: `${(SILK_COMMISSION_07_REVIEW_PORTRAIT_VIEWPORT.left / SILK_COMMISSION_07_REVIEW_PORTRAIT_FRAME_WIDTH) * 100}%`,
} as const

export const SILK_COMMISSION_07_REVIEW_PARALLAX_TRAVEL = 128
export const SILK_COMMISSION_07_REVIEW_WORLD_OVERSCAN = 80
export const SILK_COMMISSION_07_REVIEW_PARALLAX_SAFETY_MARGIN = 8
