export const SILK_COMMISSION_05_FRAME_WIDTH = 1672
export const SILK_COMMISSION_05_FRAME_HEIGHT = 941
export const SILK_COMMISSION_05_PORTRAIT_FRAME_WIDTH = 1024
export const SILK_COMMISSION_05_PORTRAIT_FRAME_HEIGHT = 1536
export const SILK_COMMISSION_05_FRAME_ALPHA_THRESHOLD = 250
export const SILK_COMMISSION_05_FRAME_COVERAGE_BAND = 8

export const SILK_COMMISSION_05_VIEWPORT = {
  left: 200,
  right: 1500,
  top: 130,
  bottom: 820,
} as const

export const SILK_COMMISSION_05_PORTRAIT_VIEWPORT = {
  left: 155,
  right: 873,
  top: 164,
  bottom: 1361,
} as const

export const SILK_COMMISSION_05_VIEWPORT_INSETS = {
  top: `${(SILK_COMMISSION_05_VIEWPORT.top / SILK_COMMISSION_05_FRAME_HEIGHT) * 100}%`,
  right: `${((SILK_COMMISSION_05_FRAME_WIDTH - SILK_COMMISSION_05_VIEWPORT.right) / SILK_COMMISSION_05_FRAME_WIDTH) * 100}%`,
  bottom: `${((SILK_COMMISSION_05_FRAME_HEIGHT - SILK_COMMISSION_05_VIEWPORT.bottom) / SILK_COMMISSION_05_FRAME_HEIGHT) * 100}%`,
  left: `${(SILK_COMMISSION_05_VIEWPORT.left / SILK_COMMISSION_05_FRAME_WIDTH) * 100}%`,
} as const

export const SILK_COMMISSION_05_PORTRAIT_VIEWPORT_INSETS = {
  top: `${(SILK_COMMISSION_05_PORTRAIT_VIEWPORT.top / SILK_COMMISSION_05_PORTRAIT_FRAME_HEIGHT) * 100}%`,
  right: `${((SILK_COMMISSION_05_PORTRAIT_FRAME_WIDTH - SILK_COMMISSION_05_PORTRAIT_VIEWPORT.right) / SILK_COMMISSION_05_PORTRAIT_FRAME_WIDTH) * 100}%`,
  bottom: `${((SILK_COMMISSION_05_PORTRAIT_FRAME_HEIGHT - SILK_COMMISSION_05_PORTRAIT_VIEWPORT.bottom) / SILK_COMMISSION_05_PORTRAIT_FRAME_HEIGHT) * 100}%`,
  left: `${(SILK_COMMISSION_05_PORTRAIT_VIEWPORT.left / SILK_COMMISSION_05_PORTRAIT_FRAME_WIDTH) * 100}%`,
} as const

export const SILK_COMMISSION_05_PARALLAX_TRAVEL = 128
export const SILK_COMMISSION_05_SCENE_OVERSCAN = 80
export const SILK_COMMISSION_05_PARALLAX_SAFETY_MARGIN = 8
