import { render, screen, within } from '@testing-library/react'
import { describe, expect, test } from 'vitest'
import { SilkChapter } from './SilkChapter'

describe('Silk chapter diegetic-wall proof', () => {
  test('owns the page-plane story and reveals world beats through authored apertures', () => {
    render(<SilkChapter />)

    const chapter = screen.getByRole('region', { name: 'Silk' })
    expect(chapter).toHaveAttribute('data-specialist-chapter', 'silk')
    expect(within(chapter).getByRole('heading', { level: 2, name: 'Silk' })).toBeVisible()
    const nameMark = chapter.querySelector<HTMLImageElement>('[data-silk-name-mark]')
    expect(nameMark?.tagName).toBe('IMG')
    expect(nameMark).toHaveAttribute('src', expect.stringContaining('media/patch/the-usual-specialists/silk-wordmark.svg'))
    expect(nameMark).toHaveAttribute('alt', '')
    const nameStrapline = chapter.querySelector('[data-silk-name-strapline]')
    expect(nameStrapline).toHaveTextContent('PRESSURE | PROVE THE ROUTE')
    expect(nameStrapline?.children).toHaveLength(0)
    expect(chapter.querySelector('[data-silk-chapter-number]')).toHaveTextContent('02')

    const commission05 = chapter.querySelector<HTMLElement>('[data-silk-commission="05"]')
    const traversal = chapter.querySelector<HTMLElement>('[data-silk-commission="06"]')
    const commission07 = chapter.querySelector<HTMLElement>('[data-silk-commission="07"]')
    const receipt = chapter.querySelector<HTMLElement>('[data-silk-receipt-peekthrough]')
    const receiptSilkCutout = chapter.querySelector<HTMLImageElement>('[data-silk-receipt-peek-cutout]')
    const commission08 = chapter.querySelector<HTMLElement>('[data-silk-commission="08"]')
    const commission09 = chapter.querySelector<HTMLElement>('[data-silk-commission="09"]')
    const traversalComposition = chapter.querySelector<HTMLElement>('[data-silk-traversal-composition]')
    const traversalPlacement = chapter.querySelector<HTMLElement>('[data-silk-traversal-placement]')
    const upperRope = traversalComposition?.querySelector<HTMLElement>('[data-specialists-rope-piece="silk-upper"]')
    const lowerRope = traversalComposition?.querySelector<HTMLElement>('[data-specialists-rope-piece="silk-lower"]')

    expect(commission05).toBeInTheDocument()
    expect(traversal).toBeInTheDocument()
    expect(commission07).toBeInTheDocument()
    expect(receipt).toBeInTheDocument()
    expect(receiptSilkCutout).toBeInTheDocument()
    expect(commission08).toBeInTheDocument()
    expect(commission09).toBeInTheDocument()
    expect(traversalComposition).toBeInTheDocument()
    expect(traversalPlacement).toContainElement(traversalComposition)
    expect(traversalPlacement?.parentElement).toBe(chapter.querySelector('[data-silk-stage]'))
    expect(upperRope?.querySelector('[data-specialists-rope-variant="taut-straight"]')).toBeInTheDocument()
    expect(lowerRope?.querySelector('[data-specialists-rope-variant="terminal-curl"]')).toBeInTheDocument()
    expect(traversalComposition?.querySelector('[data-silk-rope-anchor]')).not.toBeInTheDocument()
    expect(traversalComposition?.querySelector('[data-specialists-crossing-anchor]')).not.toBeInTheDocument()

    expect(commission05).toHaveAttribute('data-silk-aperture-owner', '05')
    const commission05Composition = commission05?.querySelector('[data-silk-aperture-composition]')
    expect(commission05Composition).toBeInTheDocument()
    expect(commission05Composition).toHaveAttribute('data-silk-aperture-composition-variant', 'commission-05')
    expect(commission05?.querySelector('[data-silk-aperture]')).not.toBeInTheDocument()
    expect(commission05?.contains(traversal)).toBe(false)
    expect(traversalComposition?.contains(traversal)).toBe(true)
    const commission05Frame = commission05Composition?.querySelector<HTMLImageElement>('[data-silk-commission-05-frame]')
    const commission05Scene = commission05Composition?.querySelector<HTMLImageElement>('[data-silk-commission-05-scene]')
    expect(commission05Scene).toHaveAttribute('src', expect.stringContaining('silk-commission-05-corridor.webp'))
    expect(commission05Scene).toHaveAttribute('alt', '')
    expect(commission05Frame).toHaveAttribute('src', expect.stringContaining('silk-commission-05-aperture-rim-heavy.webp'))
    expect(commission05Frame).toHaveAttribute('alt', '')
    expect(commission07).toHaveAttribute('data-silk-aperture-owner', '07')
    const commission07Composition = commission07?.querySelector('[data-silk-aperture-composition]')
    const commission07Frame = commission07Composition?.querySelector<HTMLImageElement>('[data-silk-commission-07-review-frame]')
    expect(commission07Composition).toHaveAttribute('data-silk-aperture-composition-variant', 'commission-07-review')
    expect(commission07?.querySelector('[data-silk-aperture]')).not.toBeInTheDocument()
    expect(commission07Frame).toHaveAttribute('src', expect.stringContaining('silk-commission-07-frame-review.webp'))
    expect(commission07Composition?.querySelector('[data-silk-commission-07-review-world]')).toBeInTheDocument()
    expect(commission07Composition?.querySelector('[data-silk-aperture-viewport-diagnostic]')).toBeInTheDocument()
    expect(commission07Composition?.querySelector('[data-silk-aperture-composition-diagnostic]')).not.toBeInTheDocument()
    expect(commission08).toHaveAttribute('data-silk-aperture-owner', '08')
    const commission08Composition = commission08?.querySelector('[data-silk-reaction-frame-composition]')
    const commission08Frame = commission08Composition?.querySelector<HTMLImageElement>('[data-silk-commission-08-review-frame]')
    expect(commission08Composition).toBeInTheDocument()
    expect(commission08Composition?.parentElement).toBe(commission08)
    expect(commission08?.querySelector('[data-silk-aperture]')).not.toBeInTheDocument()
    expect(commission08Frame).toHaveAttribute('src', expect.stringContaining('silk-commission-08-reaction-frame-review.webp'))
    expect(commission08Frame).toHaveAttribute('alt', '')
    expect(commission09).toHaveAttribute('data-silk-aperture-owner', '09')
    const commission09Composition = commission09?.querySelector('[data-silk-commission-09-composition]')
    const commission09World = commission09Composition?.querySelector('[data-silk-commission-09-standin-world]')
    const commission09Frame = commission09Composition?.querySelector<HTMLImageElement>('[data-silk-commission-09-frame-review]')
    expect(commission09Composition).toBeInTheDocument()
    expect(commission09World).toBeInTheDocument()
    expect(commission09Frame).toHaveAttribute('src', expect.stringContaining('silk-commission-09-knockthrough-frame-review.webp'))
    expect(commission09Frame).toHaveAttribute('alt', '')

    const story = chapter.querySelector('[data-silk-story-card]')
    expect(story).not.toHaveTextContent('02 / Pressure test')
    expect(story).not.toHaveTextContent('Try to break the route')
    expect(story).toHaveTextContent('Silk sees Index’s route and launches before Patch can properly begin.')
    expect(story?.querySelectorAll('p')).toHaveLength(1)

    const traversalImage = traversal?.querySelector<HTMLImageElement>('[data-silk-traversal-cutout-image]')
    expect(traversalImage).toHaveAttribute('src', expect.stringContaining('silk-commission-06-abseil-hands-free.webp'))
    expect(traversalImage).toHaveAttribute('alt', '')
    const receiptComposition = receipt?.querySelector('[data-silk-receipt-peekthrough-composition]')
    const receiptFrameCanvas = receiptComposition?.querySelector('[data-silk-receipt-frame-canvas]')
    const receiptSilkLayer = receiptComposition?.querySelector('[data-silk-receipt-peek-cutout-layer]')
    const receiptWorld = receiptComposition?.querySelector<HTMLImageElement>('[data-silk-receipt-world-image]')
    const receiptFrame = receiptComposition?.querySelector<HTMLImageElement>('[data-silk-receipt-frame-review]')
    expect(receiptComposition).toBeInTheDocument()
    expect(receiptComposition?.parentElement).toBe(receipt)
    expect(receiptWorld).toBeInTheDocument()
    expect(receiptWorld).toHaveAttribute('aria-hidden', 'true')
    expect(receiptWorld).toHaveAttribute('src', expect.stringContaining('silk-receipt-alcove-world-review.webp'))
    expect(receiptComposition?.querySelector('[data-silk-receipt-standin-world]')).not.toBeInTheDocument()
    expect(receiptFrameCanvas?.contains(receiptSilkCutout)).toBe(false)
    expect(receiptSilkLayer?.contains(receiptSilkCutout)).toBe(true)
    expect(receiptFrame).toHaveAttribute('src', expect.stringContaining('silk-receipt-peekthrough-frame-review.webp'))
    expect(receiptFrame).toHaveAttribute('alt', '')
    expect(receiptSilkCutout).toHaveAttribute('src', expect.stringContaining('silk-receipt-hole-peek-cutout-review.webp'))
    expect(receiptSilkCutout).toHaveAttribute('alt', '')
    expect(receipt).not.toHaveTextContent('Receipt peek-through')
    const reactionImage = within(commission08!).getByRole('img', { name: /Silk's eyes open in restrained surprise/i })
    expect(reactionImage).toHaveAttribute('src', expect.stringContaining('media/homepage/specialists-silk.webp'))
    expect(reactionImage).toHaveAttribute('width', '1983')
    expect(reactionImage).toHaveAttribute('height', '793')
    expect(commission09).not.toHaveTextContent('Scene pending')

    expect(commission05!.compareDocumentPosition(commission07!) & Node.DOCUMENT_POSITION_FOLLOWING).not.toBe(0)
    expect(commission07!.compareDocumentPosition(commission08!) & Node.DOCUMENT_POSITION_FOLLOWING).not.toBe(0)
    expect(commission08!.compareDocumentPosition(commission09!) & Node.DOCUMENT_POSITION_FOLLOWING).not.toBe(0)
  })
})
