#!/usr/bin/env python3
"""Generate or validate the repo-wide INDEX.md mesh for portfolio."""

from __future__ import annotations

import argparse
import os
import re
from dataclasses import dataclass
from pathlib import Path

try:
    from pathspec import PathSpec
    from pathspec.patterns.gitwildmatch import GitWildMatchPattern

    HAS_PATHSPEC = True
except ImportError:
    HAS_PATHSPEC = False


ROOT = Path(__file__).resolve().parents[1]
ALWAYS_EXCLUDED_DIR_NAMES = {
    ".git",
    ".codex",
    "__pycache__",
    "bin",
    "obj",
    "dist",
    "output",
    "node_modules",
    ".pytest_cache",
}
ALWAYS_EXCLUDED_FILE_NAMES = {".git"}


@dataclass(frozen=True)
class IndexTarget:
    path: Path
    lines: list[str]


LINK_PATTERN = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")


def load_gitignore() -> PathSpec | None:
    """Load .gitignore if pathspec is available."""
    if not HAS_PATHSPEC:
        return None

    gitignore_path = ROOT / ".gitignore"
    if not gitignore_path.exists():
        return None

    patterns: list[str] = []
    with gitignore_path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            patterns.append(line)

    if not patterns:
        return None

    return PathSpec.from_lines(GitWildMatchPattern, patterns)


GITIGNORE_SPEC = load_gitignore()


def is_under(path: Path, ancestor: Path) -> bool:
    return path == ancestor or ancestor in path.parents


def is_gitignored(path: Path) -> bool:
    if path.name in ALWAYS_EXCLUDED_DIR_NAMES:
        return True
    if path.name in ALWAYS_EXCLUDED_FILE_NAMES:
        return True

    if GITIGNORE_SPEC is None:
        return False

    relative_path = path.relative_to(ROOT)
    path_str = str(relative_path)

    if GITIGNORE_SPEC.match_file(path_str):
        return True

    if path.is_dir() and GITIGNORE_SPEC.match_file(path_str + "/"):
        return True

    for parent in path.parents:
        if parent == ROOT:
            break
        parent_relative = parent.relative_to(ROOT)
        parent_str = str(parent_relative)
        if GITIGNORE_SPEC.match_file(parent_str):
            return True
        if GITIGNORE_SPEC.match_file(parent_str + "/"):
            return True

    return False


def should_descend(child: Path) -> bool:
    if child.name in ALWAYS_EXCLUDED_DIR_NAMES:
        return False
    if is_gitignored(child):
        return False
    return True


def should_index(path: Path) -> bool:
    if path == ROOT:
        return True
    if any(part in ALWAYS_EXCLUDED_DIR_NAMES for part in path.parts):
        return False
    if is_gitignored(path):
        return False
    return True


def rel_link(current: Path, target: Path, label: str | None = None) -> str:
    rel = os.path.relpath(target, start=current).replace(os.sep, "/")
    return f"[{label or target.name}]({rel})"


def dir_link(current: Path, child: Path) -> str:
    index_md = child / "INDEX.md"
    if should_index(child):
        rel = os.path.relpath(index_md, start=current).replace(os.sep, "/")
        return f"[{child.name}]({rel})"
    if index_md.exists():
        rel = os.path.relpath(index_md, start=current).replace(os.sep, "/")
        return f"[{child.name}]({rel})"
    rel = os.path.relpath(child, start=current).replace(os.sep, "/")
    return f"[{child.name}]({rel}/)"


def render_index(path: Path) -> str:
    dirs: list[Path] = []
    files: list[Path] = []

    for entry in sorted(path.iterdir(), key=lambda p: (not p.is_dir(), p.name.casefold(), p.name)):
        if entry.name == "INDEX.md":
            continue
        if entry.is_dir():
            if not should_descend(entry):
                continue
            dirs.append(entry)
        else:
            if entry.name in ALWAYS_EXCLUDED_FILE_NAMES:
                continue
            if is_gitignored(entry):
                continue
            files.append(entry)

    lines: list[str] = ["# INDEX.md", ""]
    lines.append(
        "> **Generated by `scripts/generate_index_mesh.py`.** "
        "Do not hand-edit this file. If it is stale, regenerate it with "
        r"`python scripts/generate_index_mesh.py` (or `.\scripts\generate_index_mesh.ps1`) "
        "and commit the result. Do not reason about merging or manually updating INDEX.md files."
    )
    lines.append("")

    if dirs:
        lines.append("## Directories")
        for child in dirs:
            lines.append(f"- {dir_link(path, child)}")
        lines.append("")

    if files:
        lines.append("## Files")
        for child in files:
            lines.append(f"- {rel_link(path, child)}")
        lines.append("")

    if not dirs and not files:
        lines.append("No child entries.")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def resolve_link_target(current: Path, target: str) -> Path | None:
    if target.startswith(("http://", "https://", "mailto:")):
        return None
    clean_target = target.split("#", 1)[0]
    if not clean_target:
        return None
    resolved = (current.parent / clean_target).resolve()
    if not is_under(resolved, ROOT):
        return None
    if target.endswith("/"):
        return resolved if resolved.is_dir() else None
    return resolved if resolved.exists() else None


def validate_rendered_links(path: Path, rendered: str) -> list[str]:
    failures: list[str] = []
    for _label, raw_target in LINK_PATTERN.findall(rendered):
        resolved = resolve_link_target(path, raw_target)
        if resolved is None:
            continue
        if raw_target.endswith("/") and not resolved.is_dir():
            failures.append(f"broken-link: {path.relative_to(ROOT)} -> {raw_target}")
            continue
        if not raw_target.endswith("/") and not resolved.exists():
            failures.append(f"broken-link: {path.relative_to(ROOT)} -> {raw_target}")
    return failures


def walk_index_targets() -> list[IndexTarget]:
    targets: list[IndexTarget] = []
    for dirpath, dirnames, _filenames in os.walk(ROOT):
        current = Path(dirpath)
        dirnames[:] = sorted(
            (name for name in dirnames if should_descend(current / name)),
            key=lambda name: (name.casefold(), name),
        )
        if should_index(current):
            targets.append(IndexTarget(path=current / "INDEX.md", lines=render_index(current).splitlines()))
    return targets


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate or validate the repo-wide INDEX.md mesh")
    parser.add_argument("--check", "--validate", dest="check", action="store_true", help="validate without writing")
    args = parser.parse_args()

    targets = walk_index_targets()
    expected_paths = {target.path for target in targets}
    actual_paths = {
        path
        for path in ROOT.rglob("*")
        if path.is_file()
        and path.name == "INDEX.md"
        and not is_gitignored(path)
        and not any(part in ALWAYS_EXCLUDED_DIR_NAMES for part in path.relative_to(ROOT).parts)
    }
    unexpected = sorted(path for path in actual_paths if path not in expected_paths)
    missing = sorted(path for path in expected_paths if path not in actual_paths)

    if args.check:
        mismatches: list[str] = []
        for target in targets:
            if not target.path.exists():
                mismatches.append(f"missing: {target.path.relative_to(ROOT)}")
                continue
            current = target.path.read_text(encoding="utf-8").replace("\r\n", "\n").replace("\r", "\n")
            rendered = "\n".join(target.lines).rstrip() + "\n"
            if current != rendered:
                mismatches.append(f"stale: {target.path.relative_to(ROOT)}")
            mismatches.extend(validate_rendered_links(target.path, rendered))
        if unexpected:
            mismatches.extend(f"unexpected: {path.relative_to(ROOT)}" for path in unexpected)
        if missing:
            mismatches.extend(f"missing: {path.relative_to(ROOT)}" for path in missing)
        if mismatches:
            raise ValueError("INDEX mesh is stale or inconsistent:\n" + "\n".join(mismatches))
        print(f"OK index mesh: {len(targets)} indexes current")
        return 0

    written = 0
    for target in targets:
        rendered = "\n".join(target.lines).rstrip() + "\n"
        target.path.parent.mkdir(parents=True, exist_ok=True)
        with target.path.open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(rendered)
        written += 1

    obsolete = sorted(path for path in actual_paths if path not in expected_paths)
    for path in obsolete:
        path.unlink()

    link_failures: list[str] = []
    for target in targets:
        rendered = "\n".join(target.lines).rstrip() + "\n"
        link_failures.extend(validate_rendered_links(target.path, rendered))
    if link_failures:
        raise ValueError("INDEX mesh produced broken links:\n" + "\n".join(link_failures))

    print(f"Wrote index mesh: {written} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
